# Generated by Django 2.0 on 2017-12-24 16:03

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='description',
            field=models.CharField(default=None, max_length=2048),
        ),
        migrations.AddField(
            model_name='entity',
            name='image',
            field=models.ImageField(default=None, upload_to=media.models.Entity.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='entity',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
