# Generated by Django 2.0 on 2017-12-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20171224_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='media_type',
        ),
    ]
